# Generated by Django 5.0.2 on 2024-02-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_otromodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtroModelo',
        ),
    ]
