# Generated by Django 5.0.2 on 2024-02-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_federacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Federacion',
        ),
    ]
