# Generated by Django 5.0.2 on 2024-02-29 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_federacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='federacion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
