# Generated by Django 5.0.2 on 2024-02-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_federacion_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='federacion',
            old_name='team',
            new_name='domicilio',
        ),
        migrations.RenameField(
            model_name='federacion',
            old_name='email',
            new_name='representante',
        ),
    ]
