# Generated by Django 5.0.2 on 2024-03-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_team_federacion_domicilio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='federacion',
            old_name='role',
            new_name='nit',
        ),
    ]
