# Generated by Django 5.0.2 on 2024-03-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_role_federacion_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federacion',
            name='representante',
            field=models.CharField(max_length=255),
        ),
    ]
